### PR TITLE
Updated for more info

### PR DESCRIPTION
**Pull request by JakeRatliff**
Adding more info.

### CODE REVIEW

**Comment by melitele** [comment]
The link belongs to the 'websites' section.

**Comment by JakeRatliff** [comment]
Thanks, where is that section?

**Comment by melitele** [comment]
In the header of the .md file (between sections 'path' and 'designations').

**Comment by JakeRatliff** [comment]
Closed, added to appropriate section per @melitele comment above.

**Comment by JakeRatliff** [comment]
Thanks, I have updated it. I did a new pull request and closed out the
other one. Hope that is okay.
   Jake

**Pull request closed without merging**
